services:
  api-express-test:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://admin:supersecretpassword@mongo-express-test:27017/api?authMechanism=DEFAULT&authSource=admin
      - NODE_PATH=./
    depends_on:
      - mongo-express-test
  mongo-express-test:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=supersecretpassword
      - MONGO_INITDB_DATABASE=api
    volumes:
      - mongo-db:/data/db
      - ./mongo.conf:/etc/mongo/mongo.conf
    command: mongod --config /etc/mongo/mongo.conf
volumes:
  mongo-db: